#!/usr/bin/env bash
# Inline the four scripts into a single self-contained page for preview or
# iframe embedding. BUILD ARTEFACT — never edit pipeline-standalone.html,
# regenerate it.
#
#   ./build.sh                 -> pipeline-standalone.html
#   ./build.sh out.html        -> out.html
set -euo pipefail
cd "$(dirname "$0")"

OUT="${1:-pipeline-standalone.html}"
SRC="index.html"
FILES=(pipeline-iso.js pipeline-shapes.js pipeline-data.js pipeline-view.js)

for f in "$SRC" "${FILES[@]}"; do
  [ -f "$f" ] || { echo "missing: $f" >&2; exit 1; }
done

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# Emit everything up to the first <script src=…> line, then the inlined
# bundle in load order, then everything after the last one.
awk '/<script src="\/pipeline\//{exit} {print}' "$SRC" > "$TMP"

{
  echo "<!-- generated by build.sh — do not edit, regenerate -->"
  for f in "${FILES[@]}"; do
    echo "<script>"
    echo "/* ===== $f ===== */"
    cat "$f"
    echo "</script>"
  done
} >> "$TMP"

awk 'f{print} /<script src="\/pipeline\/pipeline-view.js"><\/script>/{f=1}' "$SRC" >> "$TMP"

mv "$TMP" "$OUT"
trap - EXIT
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
