#!/usr/bin/env bash
# Inline the four scripts into a single self-contained page for preview or
# iframe embedding. BUILD ARTEFACT — never edit pipeline-standalone.html,
# regenerate it.
#
#   ./build.sh                 -> pipeline-standalone.html
#   ./build.sh out.html        -> out.html
set -euo pipefail
cd "$(dirname "$0")"

OUT="${1:-pipeline-standalone.html}"
SRC="index.html"
# EXACTLY THE PAGE'S OWN LOAD ORDER, culls included. The awk below cuts from
# the first <script src="/pipeline/…> tag, which swallows the two /culls tags
# sitting between pipeline-shapes and pipeline-data — so anything not listed
# here is simply absent from the artefact. They were missing before, which cost
# the standalone its four cull roofs silently; and pipeline-fqshapes.js calls
# mulberry32 at LOAD time to build its read population, so without culls-pop.js
# ahead of it the whole bundle now dies with a ReferenceError rather than just
# drawing less.
FILES=(pipeline-iso.js pipeline-shapes.js ../culls/culls-pop.js ../culls/culls-draw.js pipeline-fqshapes.js pipeline-data.js pipeline-view.js)

for f in "$SRC" "${FILES[@]}"; do
  [ -f "$f" ] || { echo "missing: $f" >&2; exit 1; }
done

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# Emit everything up to the first <script src=…> line, then the inlined
# bundle in load order, then everything after the last one.
awk '/<script src="\/pipeline\//{exit} {print}' "$SRC" > "$TMP"

{
  echo "<!-- generated by build.sh — do not edit, regenerate -->"
  for f in "${FILES[@]}"; do
    echo "<script>"
    echo "/* ===== $f ===== */"
    cat "$f"
    echo "</script>"
  done
} >> "$TMP"

# the src carries a ?v=<sha> cache-buster, so match the file name, not the whole tag
awk 'f{print} /<script src="\/pipeline\/pipeline-view\.js/{f=1}' "$SRC" >> "$TMP"

mv "$TMP" "$OUT"
trap - EXIT
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
