import React, { FC, ReactNode } from "react";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";

// This import is part of the hypothetical scenario.
import { Roboto } from "next/font/google";

// Here, we're adjusting the code to specify font weights individually.
// This matches the error message's demand for "explicitly written literals."
const roboto_font = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en" className={roboto_font.className}>
      <head>
        <link rel="icon" href="/favicon.png" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  );
};

export default RootLayout;
