// src/app/layout.tsx (Server Component)
import { Roboto } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import DarkMode from "./DarkModeButton";
import { ReactNode } from "react";

const roboto_font = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "zeroshot bio",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={roboto_font.className}>
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body>
        <DarkMode>{children}</DarkMode>
        <Analytics />
      </body>
    </html>
  );
}